### ISSUE TITLE
(feature request) Provide option to count number of running background jobs

### ISSUE THREAD

**Issue by rreubenreyes** [mattgreen/lucid.fish#16]
Hi there. I've been enjoying using this prompt for quite a while now!

I do have a request. I frequently find myself suspending jobs and coming back to them later-- this is the primary way that I manage my open code editors, for example (e.g. `Ctrl+Z` to suspend open editor, `fg` to get it back later). So a count of the number of background jobs is pretty useful for me to see in the prompt.

I've actually already implemented a version of this just for my own personal config, so I'm willing to open a PR for it. Just wanted to hear your thoughts before I did so. Something like this:

```fish
function show_jobs_count # ... with a flag to enable or disable this function
    set -g jobs_count (jobs | wc -l | xargs echo -n)
    if [ $jobs_count != "0" ]
        set_color $__embark_primary_cyan
        echo -n "+$jobs_count "
    end
    set_color normal
end
```

gives:

```
~/scratch
[I] ❯ nvim whatever
fish: Job 1, 'nvim whatever' has stopped

+1 ~/scratch
[I] ❯
```

If this is too obscure of a feature to include, no worries. Thanks again for this project!

**Comment by mattgreen** [comment]
Thanks for letting me know. I think I'd prefer people put this in their right prompt, if only because it makes the spacing of the current directory inconsistent, which impedes scanning scrollback buffers. I've tended to recommend that people put such transient information in the right prompt vs the left (exception being git status, obviously).
