### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by IlanCosman** [mattgreen/lucid.fish#7]
Hi @mattgreen, I hope it's okay if I open a general questions thread here. I'm looking into making Tide asynchronous, and I think that you're the best person to ask for advice on the matter. I didn't want to just open a new issue for every question I had.

First question: You say that IPC via universal variables is a non-starter. Why is that?

I have a very simple example, but it seems to work perfectly.

```fish
function fish_prompt
    fish --command 'set -U foo (fish_git_prompt)' &

    echo $PWD $foo
end

function on_foo --on-variable foo
    commandline -f repaint
end
```

**Comment by mattgreen** [comment]
Universal variables work well for this, it's the implementation that I'm avoiding.

Specifically, they're synchronized via writing to disk, then having one fish process notify all others that they've been updated ([source](https://github.com/fish-shell/fish-shell/blob/9fb6a4ea9dae6533c1fcdc428d8730ceb897a185/src/env.cpp#L1229-L1232)). Those other fish processes then read the contents from disk. For a prompt that runs many times, I don't want to hit the disk for what amounts to a single bit of information (dirty/not dirty).

lucid's approach really only works well for constrained use cases, and mostly because I don't like much info in my prompt.

**Comment by IlanCosman** [comment]
Thanks for clearing that up! Since Tide prefers a very full-featured git prompt, i.e `fish_git_prompt`, using a universal variable for the entire prompt is probably the best method forward for async.

**Comment by IlanCosman** [comment]
After exploring this a little bit, I realize there's a pretty big issue with using universal variables, one that should have been obvious in retrospect. Unrelated fish instances will effect each other. If you go into git repo in one, the other will also display that info. I'm not sure how to get around this 😞

**Comment by mattgreen** [comment]
You can get around that by including the tty name as part of the universal variable name:

```bash
❯ tty # one tab
/dev/ttys001

❯ tty # another tab
/dev/ttys013
```

**Comment by IlanCosman** [comment]
Yeah I realized that was not actually a big issue. I didn't think of your particular solution, but something similar with`$fish_pid` at the end of the variable.
